# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]     

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: dev # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: test workspace
      run: echo ${{ github.workspace }}

    - name: test token
      run: echo ${{ github.token }}      
      
    - name: Build with Maven
    - run: mvn -B package -Pdev --file pom.xml
    - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging      

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Pdev -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Save jar
      uses: actions/upload-artifact@v3
      with:
        name: upload jar
        path: target/elevator.jar
